services:
        db:
                image: postgres:14
                environment:
                        POSTGRES_USER: ${POSTGRES_USER}
                        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                        POSTGRES_DB: ${POSTGRES_DB}
                        TZ: Asia/Manila
                ports:
                        - "5432:5432"
                volumes:
                        - postgres-data:/var/lib/postgresql/data

        app:
                image: pangilinanervin22/paysera-backend
                build: .
                ports:
                        - "${PORT}:${PORT}"
                env_file:
                        - .env
                environment:
                        DATABASE_URL: ${DATABASE_URL}
                        PORT: ${PORT}
                        NODE_ENV: "production"
                        ENABLE_DEV_GENERATORS: "false"
                        JWT_SECRET: ${JWT_SECRET}
                        ORIGIN: ${ORIGIN}
                        SALT_ROUNDS: ${SALT_ROUNDS}
                        TZ: Asia/Manila
                depends_on:
                        - db
                command: sh -c "npx prisma migrate deploy && node ./dist/src/index.js"

volumes:
        postgres-data:
